// Recipe data for The Family Recipe Collection app.
// Each recipe: id, title, category, optional source, meta fields, ingredient groups, instruction groups, notes, nutrition.

const CATEGORIES = [
  { id: "breakfast", name: "Breakfast & Bread", emoji: "🥞" },
  { id: "appetizers", name: "Appetizers & Snacks", emoji: "🍤" },
  { id: "main", name: "Lunch & Dinner", emoji: "🍲" },
  { id: "sides", name: "Side Dishes & Seasonings", emoji: "🥔" },
  { id: "desserts", name: "Desserts", emoji: "🥧" },
];

const RECIPES = [
  {
    id: "dutch-baby",
    title: "Dutch Baby (German Pancake)",
    category: "breakfast",
    meta: { Prep: "10 minutes", Cook: "30–35 minutes", Serves: "4–6" },
    ingredients: [
      { group: "Dry Ingredients", items: [
        "1 3/4 cups all-purpose flour",
        "3 tablespoons granulated sugar",
        "1 tablespoon lemon zest (optional)",
        "1/2 teaspoon salt",
        "1/8 teaspoon nutmeg",
      ]},
      { group: "Wet Ingredients", items: [
        "1 1/2 cups milk (preferably whole)",
        "6 large eggs",
        "1 1/2 teaspoons vanilla",
      ]},
      { group: "For Cooking", items: ["3 tablespoons butter"] },
    ],
    instructions: [
      { group: null, items: [
        "In a large bowl, mix together all dry ingredients.",
        "In a separate bowl, whisk together 2/3 of the wet ingredients.",
        "Add the wet mixture to the dry ingredients, stirring to combine.",
        "Add the remaining 1/3 of the wet ingredients and mix the batter until smooth.",
        "Heat a nonstick or iron skillet over medium heat on the stove.",
        "Melt 3 tablespoons of butter in the heated skillet.",
        "Once the butter is melted, pour the batter into the skillet.",
        "Immediately transfer the skillet to a cold oven.",
        "Set the oven temperature to 375°F (190°C) and bake for approximately 30-35 minutes.",
        "The Dutch baby is done when it's puffed and golden brown.",
      ]},
    ],
    notes: ["Serve immediately while puffed. Traditional toppings include powdered sugar, lemon juice, or fresh berries."],
  },
  {
    id: "classic-crepes",
    title: "Classic Crêpes",
    category: "breakfast",
    meta: { Prep: "10 minutes (plus resting)", Cook: "2–3 min per crêpe", Serves: "8–10 crêpes" },
    ingredients: [
      { group: null, items: [
        "2 eggs",
        "1 cup milk",
        "1 cup all-purpose flour",
        "Pinch of salt",
        "1 tablespoon sugar",
        "1 teaspoon vanilla extract (optional)",
        "Nutmeg for zesting (optional)",
        "2 tablespoons melted butter",
        "Water (as needed for consistency)",
      ]},
    ],
    instructions: [
      { group: "Preparing the Batter", items: [
        "In a bowl, whisk together the eggs, milk, and vanilla extract (if using).",
        "In another bowl, mix the flour, sugar, and salt.",
        "Gradually add the dry ingredients to the wet ingredients, whisking constantly to avoid lumps.",
        "Beat the mixture until smooth and lump-free.",
        "If desired, zest some nutmeg into the batter for extra flavor.",
        "Gradually add water and whisk until the batter reaches a liquid consistency.",
        "Add 2 tablespoons of melted butter to the batter and mix well.",
        "Cover the bowl and refrigerate for at least 4 hours, preferably overnight (up to 24 hours).",
      ]},
      { group: "Cooking the Crêpes", items: [
        "Remove the batter from the refrigerator and whisk briefly.",
        "Heat a non-stick skillet over medium to medium-high heat. Grease well.",
        "Pour about 1/3 to 1/2 cup of batter into the center of the pan, quickly tilting to spread evenly.",
        "Cook until edges start to brown and center is set (about 1-2 minutes).",
        "Flip and cook the other side briefly (about 30 seconds).",
        "Repeat with remaining batter, greasing pan as needed.",
      ]},
    ],
    notes: ["Serve with sweet toppings (sugar and lemon, Nutella, fruit) or savory fillings (ham and cheese, mushrooms, eggs)."],
  },
  {
    id: "buttermilk-pancakes",
    title: "Buttermilk Pancakes",
    category: "breakfast",
    meta: { Prep: "15 minutes", Cook: "20–25 minutes (full batch)", Serves: "6–8 (about 18–20 pancakes)" },
    ingredients: [
      { group: "Dry Ingredients", items: [
        "3 cups all-purpose flour",
        "1/4 cup sugar",
        "1 1/2 teaspoons salt",
        "1 tablespoon baking powder",
        "1 1/2 teaspoons baking soda",
      ]},
      { group: "Wet Ingredients", items: [
        "2 1/4 cups milk",
        "1/4 cup vegetable oil",
        "1/4 cup apple cider vinegar",
        "1 tablespoon vanilla extract",
        "3 eggs",
      ]},
    ],
    instructions: [
      { group: null, items: [
        "In a large bowl, whisk together all dry ingredients (flour, sugar, salt, baking powder, and baking soda).",
        "In a separate bowl, combine milk and apple cider vinegar. Let stand for 5 minutes to create buttermilk.",
        "Add remaining wet ingredients to the milk mixture: vegetable oil, vanilla, and eggs. Whisk until well combined.",
        "Pour the wet ingredients into the dry ingredients.",
        "Whisk until just combined. Some small lumps are okay — do not overmix.",
        "Let batter rest for 5-10 minutes while heating griddle or pan.",
        "Heat griddle or large pan over medium heat until drops of water dance and sizzle.",
        "For each pancake: pour about 1/4 cup batter onto hot griddle; cook until bubbles form on surface and edges look dry; flip and cook other side until golden brown, about 2-3 minutes per side.",
      ]},
    ],
    notes: ["The apple cider vinegar mixed with milk creates homemade buttermilk. Don't overmix the batter for fluffier pancakes."],
  },
  {
    id: "sandwich-bread",
    title: "Homemade Sandwich Bread",
    category: "breakfast",
    meta: { Prep: "20 minutes", Rise: "2–3 hours", Bake: "25 minutes", Makes: "1 loaf" },
    ingredients: [
      { group: "Wet Ingredients", items: [
        "280g warm milk (95–101°F / 35–38°C)",
        "2 tablespoons olive oil or avocado oil",
        "2 tablespoons sugar or honey",
        "2 teaspoons active dry yeast",
      ]},
      { group: "Dry Ingredients", items: [
        "3 cups all-purpose flour",
        "1/2 teaspoon salt",
      ]},
      { group: "For the Pan", items: ["Butter for greasing", "Parchment paper"] },
    ],
    instructions: [
      { group: "Mixing and First Rise", items: [
        "In a bowl, combine warm milk, oil, sugar (or honey), and yeast. Let sit for a few minutes to activate the yeast.",
        "In a separate bowl, mix flour and salt.",
        "Combine wet and dry ingredients until a soft dough forms.",
        "Stand Mixer method: knead with dough hook on high speed for 3 minutes, place in a greased bowl, cover, and let rise for 2 hours.",
        "Hand Mixing method: knead by hand about 3 minutes; place in greased bowl, cover, rise 30 minutes; stretch and fold (pull each corner up, stretch, turn bowl a quarter, repeat for a full circle), tuck dough under to form a ball; rise another 30 minutes; repeat stretch/fold/rise two more times (4 rises total, 30 min each); after the last fold, let rise 1 hour.",
      ]},
      { group: "Shaping and Second Rise", items: [
        "Grease a loaf pan with butter and line the bottom with parchment paper.",
        "Shape the dough into a rectangular loaf, folding it underneath itself.",
        "Place the shaped dough in the prepared loaf pan.",
        "Cover loosely with plastic wrap or a towel.",
        "Let rise for about 45 minutes, or until the dough is about 1 to 1.5 inches above the pan rim.",
      ]},
      { group: "Baking", items: [
        "Preheat the oven to 350°F (175°C) during the final rise.",
        "Bake the bread for approximately 25 minutes.",
        "Remove from the oven and immediately brush the top with butter.",
        "Remove from the pan and cool on a wire rack for at least 1 hour before slicing.",
      ]},
    ],
    notes: ["For softer crust, brush with butter while still warm. Store in airtight container up to 5 days."],
  },
  {
    id: "easiest-bread",
    title: "The Easiest Actually Good Bread (1 Dough, 3 Loaves)",
    category: "breakfast",
    source: "Source: Brian Lagerstrom",
    meta: { Prep: "Poolish 4–24 hrs; dough 2–3 hrs active/rising", Bake: "18–32 min, depending on style", Makes: "3 loaves" },
    ingredients: [
      { group: "Poolish", items: [
        "150 grams (2/3 cup) room temperature water",
        "Tiny pinch of yeast",
        "150 grams (1 1/4 cups) bread flour",
      ]},
      { group: "Dough", items: [
        "250 grams (1 cup) warm water (approx 86°F/30°C)",
        "2 grams (2/3 teaspoon) instant yeast",
        "300 grams ripe poolish (all of the poolish above)",
        "12 grams (2 1/2 teaspoons) salt",
        "400 grams (3 1/3 cups) bread flour",
        "50 grams (1/2 cup) whole wheat flour",
      ]},
    ],
    instructions: [
      { group: "Make the Poolish", items: [
        "In a small bowl, combine the room temperature water, pinch of yeast, and bread flour.",
        "Stir to combine and let it ferment at room temperature for at least 4 hours, but preferably 24 hours.",
      ]},
      { group: "Make the Dough", items: [
        "In a medium bowl, mix together the warm water, instant yeast, and ripe poolish.",
        "Add the salt, bread flour, and whole wheat flour to the bowl.",
        "Stir with a sturdy spoon until the ingredients are reasonably combined.",
        "Use a wet hand to squeeze and massage the dough until there are no dry spots and everything is evenly combined.",
        "Cover the bowl and let the dough ferment for 30 minutes.",
        "Perform a strength-building fold: pull a handful of dough from one side and fold it over to the other side. Rotate the bowl slightly and repeat about 7 more times, rotating after each fold.",
        "After folding, pick up the ball of dough by its side/bottom, rounding and rotating it, then set it back down to build tension across the top.",
        "Cover and let ferment at room temperature for another 30 minutes, then repeat the two prior steps.",
        "Cover and let ferment at room temperature for another 60 minutes (2 hours total fermentation). The dough should have doubled in size.",
        "Stand mixer option: use the dough hook on medium speed to replace mixing by hand, 4-5 minutes until the dough comes together and clears the bowl.",
        "Divide the dough in half — each half becomes one loaf. Choose a shaping method below.",
      ]},
      { group: "Loaf 1: Simple Ciabatta-Style (Good)", items: [
        "Flour your work surface and gently flip the dough out onto it.",
        "Flatten the dough slightly with a flat hand and pop any air bubbles.",
        "Shape the dough into a rough square.",
        "Cut the dough in half to create two equal rectangles.",
        "Transfer each loaf onto a parchment-lined sheet tray to proof.",
        "Cover with another sheet tray and let it proof 60 minutes.",
        "Preheat the oven to 480°F (250°C).",
        "Bake the loaves for 20 minutes.",
        "Let cool slightly before slicing.",
      ]},
      { group: "Loaf 2: Darker and Crustier (Better)", items: [
        "Flour your work surface and flip the dough out onto it.",
        "Flatten slightly and pop any air bubbles. Shape into a rough square.",
        "Cut the dough in half; shape each half by pulling out the sides, folding them over each other, and gently degassing any large bubbles.",
        "Flip the dough over onto the folded side and tuck everything up neatly.",
        "Transfer both shaped loaves onto a parchment-lined sheet tray. Cover with another sheet tray and let proof 60 minutes.",
        "Preheat the oven to 480°F (250°C) with a Dutch oven inside for 30 minutes.",
        "Slice the parchment in half and carefully lower 1 loaf into the preheated Dutch oven using the parchment.",
        "Cover with the lid and bake 20-22 minutes.",
        "Remove the lid and continue baking uncovered another 10-12 minutes until deeply golden brown.",
        "Repeat for the second loaf.",
      ]},
      { group: "Loaf 3: The Big Dog Boule (Best)", items: [
        "Flour your work surface and flip the dough out onto it. Pop any large bubbles and shape the dough.",
        "Grab a corner/side of the dough and pull it about 60% of the way across to the other side. Repeat all the way around the dough (7-9 folds total), popping big bubbles as you go.",
        "Flip the dough ball so the seam side is against the work surface. Roll the dough on its seam side to seal it and build tension across the top.",
        "Line a medium bowl (just bigger than the dough) with a thin kitchen towel dusted with a wheat/all-purpose flour mix. Transfer the dough ball seam-side up into the floured towel-bowl, tucking the seam once more.",
        "Fold the towel over the dough and let it proof at room temperature 45-80 minutes until doubled — it should indent and slowly spring back when poked.",
        "Preheat the oven to 480°F (250°C) with a Dutch oven inside for 30 minutes.",
        "Dust the Dutch oven generously with semolina flour or fine cornmeal to prevent sticking.",
        "Carefully flip the shaped loaf into the Dutch oven (seam side now down) and score the top with a few cuts.",
        "Cover with the lid and bake 18 minutes.",
        "Remove the lid, reduce oven temp to 465°F (240°C), and continue baking another 20-25 minutes.",
        "Transfer to a wire rack to cool.",
      ]},
    ],
    notes: ["All three loaves come from the same dough — only the shaping and baking method changes. Start the poolish the night before you plan to bake."],
  },
  {
    id: "crab-dip",
    title: "Million Dollar Shrimp & Crab Dip",
    category: "appetizers",
    source: "Source: Stacey | SouthernDiscourse.com",
    meta: { Prep: "10 minutes", Cook: "30 minutes", Resting: "10 minutes", Serves: "8" },
    ingredients: [
      { group: null, items: [
        "1 lb salad shrimp, patted dry",
        "6 oz lump crab meat",
        "1/2 cup cooked bacon pieces",
        "8 oz cream cheese, room temperature",
        "1/4 cup sour cream",
        "1/4 cup mayonnaise",
        "1/2 cup grated pepper Jack cheese",
        "1/4 cup grated sharp cheddar cheese",
        "1/4 cup shredded Parmesan cheese",
        "1/4 cup finely diced red bell pepper",
        "1/4 cup finely sliced green onion, plus 2 tablespoons for garnish",
        "1 tablespoon lemon juice",
        "1 1/2 teaspoons Worcestershire sauce",
        "1 teaspoon garlic powder",
        "1 teaspoon salt",
        "1/2 teaspoon paprika",
        "1/4 teaspoon ground black pepper",
      ]},
    ],
    instructions: [
      { group: null, items: [
        "Preheat oven to 350°F.",
        "In a medium bowl, use a hand mixer to blend cream cheese, sour cream, and mayo together. Add grated cheeses, bell pepper, and onion, and blend. Mix in seasonings, lemon juice, and Worcestershire sauce.",
        "Using a fork, stir in the lump crab and bacon. Fold in salad shrimp.",
        "When mixed well, spoon dip into a 1.5-quart dish and bake for 30-35 minutes, until the top is golden brown and edges bubble. Remove from oven and let rest for 10 minutes.",
        "Add extra diced green onion as garnish before serving.",
      ]},
    ],
  },
  {
    id: "lentils-rice",
    title: "Lentils over Rice",
    category: "main",
    meta: { Prep: "15 minutes", Cook: "25 minutes", Serves: "4–6" },
    ingredients: [
      { group: null, items: [
        "1 can of lentils",
        "6 slices of uncooked bacon",
        "2 cloves of garlic, minced",
        "2 tablespoons of olive oil",
        "Salt and pepper to taste",
        "1/2 onion, chopped",
        "1/2 green pepper, chopped",
        "1 tablespoon of sofrito",
        "Small amount of white vinegar (less than 1/2 teaspoon)",
        "1 bay leaf",
        "1 package of Sazón seasoning",
        "1 chicken bouillon cube",
        "Water (amount as per bouillon cube instructions)",
      ]},
    ],
    instructions: [
      { group: null, items: [
        "Cut the bacon into small pieces and fry in a saucepan until crisp.",
        "Add chopped onions and green peppers to the pan with the bacon. Cook until translucent.",
        "Add minced garlic and cook for another minute.",
        "Add one bay leaf and the package of Sazón seasoning. Stir to combine all ingredients.",
        "Dissolve the chicken bouillon cube in the appropriate amount of hot water as per the cube's instructions.",
        "Pour the bouillon mixture into the pan and let the ingredients come together.",
        "Add the can of lentils (including the liquid) to the pan.",
        "Stir in the sofrito.",
        "Let the mixture simmer and come together.",
        "Season with salt and pepper to taste.",
        "Add a little bit of olive oil for richness.",
        "Stir in less than 1/2 teaspoon of white vinegar.",
        "Simmer for a few more minutes to let the flavors meld.",
        "Serve over cooked rice.",
      ]},
    ],
    notes: ["This dish is great for meal prep and tastes even better the next day."],
  },
  {
    id: "gumbo",
    title: "Easy Shrimp & Sausage Gumbo",
    category: "main",
    source: "Source: Stacey | SouthernDiscourse.com",
    meta: { Prep: "20 minutes", Cook: "1 hour", Total: "1 hour 20 minutes", Serves: "10" },
    ingredients: [
      { group: "Equipment", items: ["8-quart Dutch oven (or stock pot)"] },
      { group: null, items: [
        "1/2 cup butter (1 stick)",
        "3/4 cup all-purpose flour",
        "1 large yellow onion, diced",
        "3 stalks celery, diced",
        "1 large green bell pepper, diced",
        "1 tablespoon minced garlic (about 4 cloves)",
        "64 ounces chicken broth (8 cups)",
        "2 cans diced tomatoes with green chilies (14.5 oz each)",
        "1 1/2 pounds smoked sausage, sliced",
        "2 cups cut okra, frozen or fresh",
        "3-4 bay leaves",
        "1 teaspoon black pepper",
        "1 teaspoon Italian seasoning",
        "1/2 teaspoon ground coriander",
        "1/2 teaspoon salt",
        "1/4 teaspoon ground cumin",
        "1/4 teaspoon cayenne pepper",
        "2 pounds large shrimp, peeled and deveined",
        "1/4 cup chopped fresh parsley",
      ]},
    ],
    instructions: [
      { group: null, items: [
        "In a large stockpot, melt butter over medium-high heat. Whisk in flour. Cook for 5-7 minutes, whisking constantly, until the roux is golden brown (like peanut butter) with a nutty aroma.",
        "Add onion, celery, bell pepper, and garlic. Cook until onion is translucent (the roux will coat the veggies and continue to brown as they cook).",
        "Whisk in about half of the chicken broth until all the flour is incorporated and the base is smooth.",
        "Add the rest of the broth, diced tomatoes and green chilies, bay leaves, and all the spices. Bring to a low boil over medium heat. Add okra and smoked sausage. Reduce heat to medium-low and simmer until okra is completely cooked.",
        "Stir in shrimp. Cook for 5-8 minutes until pink and firm. Stir in the chopped fresh parsley, and serve.",
      ]},
    ],
    notes: [
      "Recipe variations: add 2 shredded chicken thighs or breasts (great use for leftover rotisserie chicken), 1/2 pound crab meat, or 1 pound crawfish tails for extra protein.",
      "You can brown the sliced sausage in a skillet before adding it for a seared flavor, but you'll lose some of the drippings and robust flavor the sausage adds when cooked directly in the dish.",
      "Serve over rice.",
    ],
  },
  {
    id: "scalloped-potatoes",
    title: "Low-Fat Scalloped Potatoes",
    category: "main",
    meta: { Prep: "20 minutes", Cook: "60–65 minutes", Serves: "6–8" },
    ingredients: [
      { group: "For the Cheese Sauce", items: [
        "2 tablespoons butter",
        "3 tablespoons all-purpose flour",
        "1 teaspoon salt",
        "1/4 teaspoon pepper",
        "1-1/2 cups fat-free milk",
        "1/2 cup shredded reduced-fat cheddar cheese",
      ]},
      { group: "For the Potatoes", items: [
        "2 pounds potatoes, peeled and thinly sliced (about 4 cups)",
        "1 cup thinly sliced onions",
        "Cooking spray",
      ]},
    ],
    instructions: [
      { group: null, items: [
        "Preheat oven to 350°F (175°C).",
        "Make the cheese sauce: melt butter in a small saucepan; stir in flour, salt, and pepper until smooth; gradually whisk in milk; bring to a boil, stirring constantly; cook and stir until thickened, about 2 minutes; remove from heat and stir in cheese until melted.",
        "Assemble the dish: coat an 8-inch square baking dish with cooking spray; layer half of the sliced potatoes in the dish; add 1/2 cup sliced onions; pour half of the cheese sauce; repeat layers with remaining ingredients.",
        "Baking: cover and bake for 50 minutes; uncover and bake an additional 10-15 minutes until bubbly and potatoes are tender.",
      ]},
    ],
    nutrition: { title: "Nutrition Facts (per 3/4 cup serving)", items: ["Calories: 215", "Fat: 6g (4g saturated fat)", "Cholesterol: 18mg", "Sodium: 523mg", "Carbohydrate: 32g (5g sugars, 3g fiber)", "Protein: 8g"] },
  },
  {
    id: "fish-fry-mix",
    title: "Homemade Cornmeal Fish Fry Mix",
    category: "sides",
    source: "Source: Stacey | SouthernDiscourse.com",
    meta: { Prep: "2 minutes", Makes: "enough to coat 1.5 lbs fish fillets" },
    ingredients: [
      { group: null, items: [
        "1 3/4 cups white or yellow cornmeal",
        "1/4 cup flour",
        "1 tablespoon paprika",
        "2 teaspoons salt",
        "2 teaspoons lemon pepper",
        "1/2 teaspoon cayenne pepper",
      ]},
    ],
    instructions: [
      { group: null, items: [
        "Place all ingredients in a plastic bowl with a lid or in a brown paper lunch bag. Shake vigorously to mix all ingredients.",
        "Drop cleaned and washed fish fillets into the bowl or bag filled with cornmeal mix and shake vigorously again to coat. Drop fish into canola or peanut oil heated to 375°F to deep fry for 5-7 minutes, or until fish is golden brown.",
      ]},
    ],
    notes: [
      "For an extra flavor kick, add 1/2 teaspoon garlic powder and 1/2 teaspoon onion powder to the cornmeal mix.",
      "Nutrition below reflects all of the cornmeal mix; the fillet value varies depending on size and type of fish.",
    ],
    nutrition: { title: "Nutrition Facts (whole batch of mix)", items: ["Calories: 810 kcal", "Carbohydrates: 156g", "Protein: 21g", "Fat: 12g", "Sodium: 3112mg", "Sugar: 4g"] },
  },
  {
    id: "pumpkin-pie",
    title: "Pumpkin Pie with Sugared Cranberries",
    category: "desserts",
    meta: { Prep: "45 minutes (plus overnight for cranberries)", Cook: "55–60 minutes", Serves: "8–10" },
    ingredients: [
      { group: "Sugared Cranberries", items: [
        "1 cup (100g) fresh cranberries (not frozen)",
        "3/4 cup (180ml) water",
        "1 and 1/4 cups (250g) granulated sugar, divided",
      ]},
      { group: "Pie Crust", items: [
        "Homemade Pie Dough (full recipe for 2 crusts: bottom and leaf decor)",
        "Egg wash: 1 large egg beaten with 1 tablespoon milk",
      ]},
      { group: "Pumpkin Filling", items: [
        "One 15-ounce can (425g) pumpkin puree",
        "3 large eggs",
        "1 and 1/4 cups (250g) packed light or dark brown sugar",
        "1 tablespoon (8g) cornstarch",
        "1/2 teaspoon salt",
        "1 and 1/2 teaspoons ground cinnamon",
        "1/2 teaspoon ground ginger",
        "1/4 teaspoon ground or freshly grated nutmeg",
        "1/8 teaspoon ground cloves",
        "1/8 teaspoon fresh ground black pepper",
        "1 cup (240ml) heavy cream",
        "1/4 cup (60ml) milk",
      ]},
    ],
    instructions: [
      { group: "Sugared Cranberries (Start Night Before)", items: [
        "Place cranberries in a large heatproof bowl.",
        "Heat water and 3/4 cup sugar in saucepan until sugar dissolves.",
        "Cool syrup 5 minutes, pour over cranberries, stir.",
        "Cover, rest 15 minutes.",
        "Transfer cranberries to lined baking sheet, dry 1 hour.",
        "Toss in remaining 1/2 cup sugar.",
        "Dry again 1+ hour. Store in refrigerator up to 3 days.",
      ]},
      { group: "Pie Crust", items: [
        "Preheat oven to 375°F (190°C).",
        "Roll dough into 12-inch circle.",
        "Place in 9×2-inch deep dish pie dish.",
        "Crimp or flute edges, brush with egg wash.",
        "Line with parchment, fill with weights.",
        "Par-bake 10 minutes.",
        "Remove weights, prick bottom, bake 7-8 minutes more.",
      ]},
      { group: "Filling and Assembly", items: [
        "Whisk together pumpkin, eggs, and brown sugar; add cornstarch, salt, and spices; stir in cream and milk.",
        "Pour into warm crust (fill 3/4 full).",
        "Bake 55-60 minutes: cover edges with foil after 25 minutes; center should be slightly wobbly; check doneness starting at 50 minutes.",
        "Cool completely (3+ hours) before decorating.",
        "Garnish with sugared cranberries and pie crust leaves.",
      ]},
    ],
    notes: ["Cover leftovers tightly. Store in refrigerator up to 5 days."],
  },
];
