// Recipe data for The Family Recipe Collection app.
// Each recipe: id, title, category, optional source, meta fields, ingredient groups, instruction groups, notes, nutrition.

const CATEGORIES = [
  { id: "breakfast", name: "Breakfast & Bread", emoji: "🥞" },
  { id: "appetizers", name: "Appetizers & Snacks", emoji: "🍤" },
  { id: "main", name: "Lunch & Dinner", emoji: "🍲" },
  { id: "sides", name: "Side Dishes & Seasonings", emoji: "🥔" },
  { id: "desserts", name: "Desserts", emoji: "🥧" },
];

const RECIPES = [
  {
    id: "dutch-baby",
    title: "Dutch Baby (German Pancake)",
    category: "breakfast",
    meta: { Prep: "10 minutes", Cook: "30–35 minutes", Serves: "4–6" },
    ingredients: [
      { group: "Dry Ingredients", items: [
        "1 3/4 cups all-purpose flour",
        "3 tablespoons granulated sugar",
        "1 tablespoon lemon zest (optional)",
        "1/2 teaspoon salt",
        "1/8 teaspoon nutmeg",
      ]},
      { group: "Wet Ingredients", items: [
        "1 1/2 cups milk (preferably whole)",
        "6 large eggs",
        "1 1/2 teaspoons vanilla",
      ]},
      { group: "For Cooking", items: ["3 tablespoons butter"] },
    ],
    instructions: [
      { group: null, items: [
        "In a large bowl, mix together all dry ingredients.",
        "In a separate bowl, whisk together 2/3 of the wet ingredients.",
        "Add the wet mixture to the dry ingredients, stirring to combine.",
        "Add the remaining 1/3 of the wet ingredients and mix the batter until smooth.",
        "Heat a nonstick or iron skillet over medium heat on the stove.",
        "Melt 3 tablespoons of butter in the heated skillet.",
        "Once the butter is melted, pour the batter into the skillet.",
        "Immediately transfer the skillet to a cold oven.",
        "Set the oven temperature to 375°F (190°C) and bake for approximately 30-35 minutes.",
        "The Dutch baby is done when it's puffed and golden brown.",
      ]},
    ],
    notes: ["Serve immediately while puffed. Traditional toppings include powdered sugar, lemon juice, or fresh berries."],
  },
  {
    id: "classic-crepes",
    title: "Classic Crêpes",
    category: "breakfast",
    meta: { Prep: "10 minutes (plus resting)", Cook: "2–3 min per crêpe", Serves: "8–10 crêpes" },
    ingredients: [
      { group: null, items: [
        "2 eggs",
        "1 cup milk",
        "1 cup all-purpose flour",
        "Pinch of salt",
        "1 tablespoon sugar",
        "1 teaspoon vanilla extract (optional)",
        "Nutmeg for zesting (optional)",
        "2 tablespoons melted butter",
        "Water (as needed for consistency)",
      ]},
    ],
    instructions: [
      { group: "Preparing the Batter", items: [
        "In a bowl, whisk together the eggs, milk, and vanilla extract (if using).",
        "In another bowl, mix the flour, sugar, and salt.",
        "Gradually add the dry ingredients to the wet ingredients, whisking constantly to avoid lumps.",
        "Beat the mixture until smooth and lump-free.",
        "If desired, zest some nutmeg into the batter for extra flavor.",
        "Gradually add water and whisk until the batter reaches a liquid consistency.",
        "Add 2 tablespoons of melted butter to the batter and mix well.",
        "Cover the bowl and refrigerate for at least 4 hours, preferably overnight (up to 24 hours).",
      ]},
      { group: "Cooking the Crêpes", items: [
        "Remove the batter from the refrigerator and whisk briefly.",
        "Heat a non-stick skillet over medium to medium-high heat. Grease well.",
        "Pour about 1/3 to 1/2 cup of batter into the center of the pan, quickly tilting to spread evenly.",
        "Cook until edges start to brown and center is set (about 1-2 minutes).",
        "Flip and cook the other side briefly (about 30 seconds).",
        "Repeat with remaining batter, greasing pan as needed.",
      ]},
    ],
    notes: ["Serve with sweet toppings (sugar and lemon, Nutella, fruit) or savory fillings (ham and cheese, mushrooms, eggs)."],
  },
  {
    id: "buttermilk-pancakes",
    title: "Buttermilk Pancakes",
    category: "breakfast",
    meta: { Prep: "15 minutes", Cook: "20–25 minutes (full batch)", Serves: "6–8 (about 18–20 pancakes)" },
    ingredients: [
      { group: "Dry Ingredients", items: [
        "3 cups all-purpose flour",
        "1/4 cup sugar",
        "1 1/2 teaspoons salt",
        "1 tablespoon baking powder",
        "1 1/2 teaspoons baking soda",
      ]},
      { group: "Wet Ingredients", items: [
        "2 1/4 cups milk",
        "1/4 cup vegetable oil",
        "1/4 cup apple cider vinegar",
        "1 tablespoon vanilla extract",
        "3 eggs",
      ]},
    ],
    instructions: [
      { group: null, items: [
        "In a large bowl, whisk together all dry ingredients (flour, sugar, salt, baking powder, and baking soda).",
        "In a separate bowl, combine milk and apple cider vinegar. Let stand for 5 minutes to create buttermilk.",
        "Add remaining wet ingredients to the milk mixture: vegetable oil, vanilla, and eggs. Whisk until well combined.",
        "Pour the wet ingredients into the dry ingredients.",
        "Whisk until just combined. Some small lumps are okay — do not overmix.",
        "Let batter rest for 5-10 minutes while heating griddle or pan.",
        "Heat griddle or large pan over medium heat until drops of water dance and sizzle.",
        "For each pancake: pour about 1/4 cup batter onto hot griddle; cook until bubbles form on surface and edges look dry; flip and cook other side until golden brown, about 2-3 minutes per side.",
      ]},
    ],
    notes: ["The apple cider vinegar mixed with milk creates homemade buttermilk. Don't overmix the batter for fluffier pancakes."],
  },
  {
    id: "sandwich-bread",
    title: "Homemade Sandwich Bread",
    category: "breakfast",
    meta: { Prep: "20 minutes", Rise: "2–3 hours", Bake: "25 minutes", Makes: "1 loaf" },
    ingredients: [
      { group: "Wet Ingredients", items: [
        "280g warm milk (95–101°F / 35–38°C)",
        "2 tablespoons olive oil or avocado oil",
        "2 tablespoons sugar or honey",
        "2 teaspoons active dry yeast",
      ]},
      { group: "Dry Ingredients", items: [
        "3 cups all-purpose flour",
        "1/2 teaspoon salt",
      ]},
      { group: "For the Pan", items: ["Butter for greasing", "Parchment paper"] },
    ],
    instructions: [
      { group: "Mixing and First Rise", items: [
        "In a bowl, combine warm milk, oil, sugar (or honey), and yeast. Let sit for a few minutes to activate the yeast.",
        "In a separate bowl, mix flour and salt.",
        "Combine wet and dry ingredients until a soft dough forms.",
        "Stand Mixer method: knead with dough hook on high speed for 3 minutes, place in a greased bowl, cover, and let rise for 2 hours.",
        "Hand Mixing method: knead by hand about 3 minutes; place in greased bowl, cover, rise 30 minutes; stretch and fold (pull each corner up, stretch, turn bowl a quarter, repeat for a full circle), tuck dough under to form a ball; rise another 30 minutes; repeat stretch/fold/rise two more times (4 rises total, 30 min each); after the last fold, let rise 1 hour.",
      ]},
      { group: "Shaping and Second Rise", items: [
        "Grease a loaf pan with butter and line the bottom with parchment paper.",
        "Shape the dough into a rectangular loaf, folding it underneath itself.",
        "Place the shaped dough in the prepared loaf pan.",
        "Cover loosely with plastic wrap or a towel.",
        "Let rise for about 45 minutes, or until the dough is about 1 to 1.5 inches above the pan rim.",
      ]},
      { group: "Baking", items: [
        "Preheat the oven to 350°F (175°C) during the final rise.",
        "Bake the bread for approximately 25 minutes.",
        "Remove from the oven and immediately brush the top with butter.",
        "Remove from the pan and cool on a wire rack for at least 1 hour before slicing.",
      ]},
    ],
    notes: ["For softer crust, brush with butter while still warm. Store in airtight container up to 5 days."],
  },
  {
    id: "easiest-bread",
    title: "The Easiest Actually Good Bread (1 Dough, 3 Loaves)",
    category: "breakfast",
    source: "Source: Brian Lagerstrom",
    meta: { Prep: "Poolish 4–24 hrs; dough 2–3 hrs active/rising", Bake: "18–32 min, depending on style", Makes: "3 loaves" },
    ingredients: [
      { group: "Poolish", items: [
        "150 grams (2/3 cup) room temperature water",
        "Tiny pinch of yeast",
        "150 grams (1 1/4 cups) bread flour",
      ]},
      { group: "Dough", items: [
        "250 grams (1 cup) warm water (approx 86°F/30°C)",
        "2 grams (2/3 teaspoon) instant yeast",
        "300 grams ripe poolish (all of the poolish above)",
        "12 grams (2 1/2 teaspoons) salt",
        "400 grams (3 1/3 cups) bread flour",
        "50 grams (1/2 cup) whole wheat flour",
      ]},
    ],
    instructions: [
      { group: "Make the Poolish", items: [
        "In a small bowl, combine the room temperature water, pinch of yeast, and bread flour.",
        "Stir to combine and let it ferment at room temperature for at least 4 hours, but preferably 24 hours.",
      ]},
      { group: "Make the Dough", items: [
        "In a medium bowl, mix together the warm water, instant yeast, and ripe poolish.",
        "Add the salt, bread flour, and whole wheat flour to the bowl.",
        "Stir with a sturdy spoon until the ingredients are reasonably combined.",
        "Use a wet hand to squeeze and massage the dough until there are no dry spots and everything is evenly combined.",
        "Cover the bowl and let the dough ferment for 30 minutes.",
        "Perform a strength-building fold: pull a handful of dough from one side and fold it over to the other side. Rotate the bowl slightly and repeat about 7 more times, rotating after each fold.",
        "After folding, pick up the ball of dough by its side/bottom, rounding and rotating it, then set it back down to build tension across the top.",
        "Cover and let ferment at room temperature for another 30 minutes, then repeat the two prior steps.",
        "Cover and let ferment at room temperature for another 60 minutes (2 hours total fermentation). The dough should have doubled in size.",
        "Stand mixer option: use the dough hook on medium speed to replace mixing by hand, 4-5 minutes until the dough comes together and clears the bowl.",
        "Divide the dough in half — each half becomes one loaf. Choose a shaping method below.",
      ]},
      { group: "Loaf 1: Simple Ciabatta-Style (Good)", items: [
        "Flour your work surface and gently flip the dough out onto it.",
        "Flatten the dough slightly with a flat hand and pop any air bubbles.",
        "Shape the dough into a rough square.",
        "Cut the dough in half to create two equal rectangles.",
        "Transfer each loaf onto a parchment-lined sheet tray to proof.",
        "Cover with another sheet tray and let it proof 60 minutes.",
        "Preheat the oven to 480°F (250°C).",
        "Bake the loaves for 20 minutes.",
        "Let cool slightly before slicing.",
      ]},
      { group: "Loaf 2: Darker and Crustier (Better)", items: [
        "Flour your work surface and flip the dough out onto it.",
        "Flatten slightly and pop any air bubbles. Shape into a rough square.",
        "Cut the dough in half; shape each half by pulling out the sides, folding them over each other, and gently degassing any large bubbles.",
        "Flip the dough over onto the folded side and tuck everything up neatly.",
        "Transfer both shaped loaves onto a parchment-lined sheet tray. Cover with another sheet tray and let proof 60 minutes.",
        "Preheat the oven to 480°F (250°C) with a Dutch oven inside for 30 minutes.",
        "Slice the parchment in half and carefully lower 1 loaf into the preheated Dutch oven using the parchment.",
        "Cover with the lid and bake 20-22 minutes.",
        "Remove the lid and continue baking uncovered another 10-12 minutes until deeply golden brown.",
        "Repeat for the second loaf.",
      ]},
      { group: "Loaf 3: The Big Dog Boule (Best)", items: [
        "Flour your work surface and flip the dough out onto it. Pop any large bubbles and shape the dough.",
        "Grab a corner/side of the dough and pull it about 60% of the way across to the other side. Repeat all the way around the dough (7-9 folds total), popping big bubbles as you go.",
        "Flip the dough ball so the seam side is against the work surface. Roll the dough on its seam side to seal it and build tension across the top.",
        "Line a medium bowl (just bigger than the dough) with a thin kitchen towel dusted with a wheat/all-purpose flour mix. Transfer the dough ball seam-side up into the floured towel-bowl, tucking the seam once more.",
        "Fold the towel over the dough and let it proof at room temperature 45-80 minutes until doubled — it should indent and slowly spring back when poked.",
        "Preheat the oven to 480°F (250°C) with a Dutch oven inside for 30 minutes.",
        "Dust the Dutch oven generously with semolina flour or fine cornmeal to prevent sticking.",
        "Carefully flip the shaped loaf into the Dutch oven (seam side now down) and score the top with a few cuts.",
        "Cover with the lid and bake 18 minutes.",
        "Remove the lid, reduce oven temp to 465°F (240°C), and continue baking another 20-25 minutes.",
        "Transfer to a wire rack to cool.",
      ]},
    ],
    notes: ["All three loaves come from the same dough — only the shaping and baking method changes. Start the poolish the night before you plan to bake."],
  },
  {
    id: "crab-dip",
    title: "Million Dollar Shrimp & Crab Dip",
    category: "appetizers",
    source: "Source: Stacey | SouthernDiscourse.com",
    meta: { Prep: "10 minutes", Cook: "30 minutes", Resting: "10 minutes", Serves: "8" },
    ingredients: [
      { group: null, items: [
        "1 lb salad shrimp, patted dry",
        "6 oz lump crab meat",
        "1/2 cup cooked bacon pieces",
        "8 oz cream cheese, room temperature",
        "1/4 cup sour cream",
        "1/4 cup mayonnaise",
        "1/2 cup grated pepper Jack cheese",
        "1/4 cup grated sharp cheddar cheese",
        "1/4 cup shredded Parmesan cheese",
        "1/4 cup finely diced red bell pepper",
        "1/4 cup finely sliced green onion, plus 2 tablespoons for garnish",
        "1 tablespoon lemon juice",
        "1 1/2 teaspoons Worcestershire sauce",
        "1 teaspoon garlic powder",
        "1 teaspoon salt",
        "1/2 teaspoon paprika",
        "1/4 teaspoon ground black pepper",
      ]},
    ],
    instructions: [
      { group: null, items: [
        "Preheat oven to 350°F.",
        "In a medium bowl, use a hand mixer to blend cream cheese, sour cream, and mayo together. Add grated cheeses, bell pepper, and onion, and blend. Mix in seasonings, lemon juice, and Worcestershire sauce.",
        "Using a fork, stir in the lump crab and bacon. Fold in salad shrimp.",
        "When mixed well, spoon dip into a 1.5-quart dish and bake for 30-35 minutes, until the top is golden brown and edges bubble. Remove from oven and let rest for 10 minutes.",
        "Add extra diced green onion as garnish before serving.",
      ]},
    ],
  },
  {
    id: "lentils-rice",
    title: "Lentils over Rice",
    category: "main",
    meta: { Prep: "15 minutes", Cook: "25 minutes", Serves: "4–6" },
    ingredients: [
      { group: null, items: [
        "1 can of lentils",
        "6 slices of uncooked bacon",
        "2 cloves of garlic, minced",
        "2 tablespoons of olive oil",
        "Salt and pepper to taste",
        "1/2 onion, chopped",
        "1/2 green pepper, chopped",
        "1 tablespoon of sofrito",
        "Small amount of white vinegar (less than 1/2 teaspoon)",
        "1 bay leaf",
        "1 package of Sazón seasoning",
        "1 chicken bouillon cube",
        "Water (amount as per bouillon cube instructions)",
      ]},
    ],
    instructions: [
      { group: null, items: [
        "Cut the bacon into small pieces and fry in a saucepan until crisp.",
        "Add chopped onions and green peppers to the pan with the bacon. Cook until translucent.",
        "Add minced garlic and cook for another minute.",
        "Add one bay leaf and the package of Sazón seasoning. Stir to combine all ingredients.",
        "Dissolve the chicken bouillon cube in the appropriate amount of hot water as per the cube's instructions.",
        "Pour the bouillon mixture into the pan and let the ingredients come together.",
        "Add the can of lentils (including the liquid) to the pan.",
        "Stir in the sofrito.",
        "Let the mixture simmer and come together.",
        "Season with salt and pepper to taste.",
        "Add a little bit of olive oil for richness.",
        "Stir in less than 1/2 teaspoon of white vinegar.",
        "Simmer for a few more minutes to let the flavors meld.",
        "Serve over cooked rice.",
      ]},
    ],
    notes: ["This dish is great for meal prep and tastes even better the next day."],
  },
  {
    id: "gumbo",
    title: "Easy Shrimp & Sausage Gumbo",
    category: "main",
    source: "Source: Stacey | SouthernDiscourse.com",
    meta: { Prep: "20 minutes", Cook: "1 hour", Total: "1 hour 20 minutes", Serves: "10" },
    ingredients: [
      { group: "Equipment", items: ["8-quart Dutch oven (or stock pot)"] },
      { group: null, items: [
        "1/2 cup butter (1 stick)",
        "3/4 cup all-purpose flour",
        "1 large yellow onion, diced",
        "3 stalks celery, diced",
        "1 large green bell pepper, diced",
        "1 tablespoon minced garlic (about 4 cloves)",
        "64 ounces chicken broth (8 cups)",
        "2 cans diced tomatoes with green chilies (14.5 oz each)",
        "1 1/2 pounds smoked sausage, sliced",
        "2 cups cut okra, frozen or fresh",
        "3-4 bay leaves",
        "1 teaspoon black pepper",
        "1 teaspoon Italian seasoning",
        "1/2 teaspoon ground coriander",
        "1/2 teaspoon salt",
        "1/4 teaspoon ground cumin",
        "1/4 teaspoon cayenne pepper",
        "2 pounds large shrimp, peeled and deveined",
        "1/4 cup chopped fresh parsley",
      ]},
    ],
    instructions: [
      { group: null, items: [
        "In a large stockpot, melt butter over medium-high heat. Whisk in flour. Cook for 5-7 minutes, whisking constantly, until the roux is golden brown (like peanut butter) with a nutty aroma.",
        "Add onion, celery, bell pepper, and garlic. Cook until onion is translucent (the roux will coat the veggies and continue to brown as they cook).",
        "Whisk in about half of the chicken broth until all the flour is incorporated and the base is smooth.",
        "Add the rest of the broth, diced tomatoes and green chilies, bay leaves, and all the spices. Bring to a low boil over medium heat. Add okra and smoked sausage. Reduce heat to medium-low and simmer until okra is completely cooked.",
        "Stir in shrimp. Cook for 5-8 minutes until pink and firm. Stir in the chopped fresh parsley, and serve.",
      ]},
    ],
    notes: [
      "Recipe variations: add 2 shredded chicken thighs or breasts (great use for leftover rotisserie chicken), 1/2 pound crab meat, or 1 pound crawfish tails for extra protein.",
      "You can brown the sliced sausage in a skillet before adding it for a seared flavor, but you'll lose some of the drippings and robust flavor the sausage adds when cooked directly in the dish.",
      "Serve over rice.",
    ],
  },
  {
    id: "scalloped-potatoes",
    title: "Low-Fat Scalloped Potatoes",
    category: "main",
    meta: { Prep: "20 minutes", Cook: "60–65 minutes", Serves: "6–8" },
    ingredients: [
      { group: "For the Cheese Sauce", items: [
        "2 tablespoons butter",
        "3 tablespoons all-purpose flour",
        "1 teaspoon salt",
        "1/4 teaspoon pepper",
        "1-1/2 cups fat-free milk",
        "1/2 cup shredded reduced-fat cheddar cheese",
      ]},
      { group: "For the Potatoes", items: [
        "2 pounds potatoes, peeled and thinly sliced (about 4 cups)",
        "1 cup thinly sliced onions",
        "Cooking spray",
      ]},
    ],
    instructions: [
      { group: null, items: [
        "Preheat oven to 350°F (175°C).",
        "Make the cheese sauce: melt butter in a small saucepan; stir in flour, salt, and pepper until smooth; gradually whisk in milk; bring to a boil, stirring constantly; cook and stir until thickened, about 2 minutes; remove from heat and stir in cheese until melted.",
        "Assemble the dish: coat an 8-inch square baking dish with cooking spray; layer half of the sliced potatoes in the dish; add 1/2 cup sliced onions; pour half of the cheese sauce; repeat layers with remaining ingredients.",
        "Baking: cover and bake for 50 minutes; uncover and bake an additional 10-15 minutes until bubbly and potatoes are tender.",
      ]},
    ],
    nutrition: { title: "Nutrition Facts (per 3/4 cup serving)", items: ["Calories: 215", "Fat: 6g (4g saturated fat)", "Cholesterol: 18mg", "Sodium: 523mg", "Carbohydrate: 32g (5g sugars, 3g fiber)", "Protein: 8g"] },
  },
  {
    id: "fish-fry-mix",
    title: "Homemade Cornmeal Fish Fry Mix",
    category: "sides",
    source: "Source: Stacey | SouthernDiscourse.com",
    meta: { Prep: "2 minutes", Makes: "enough to coat 1.5 lbs fish fillets" },
    ingredients: [
      { group: null, items: [
        "1 3/4 cups white or yellow cornmeal",
        "1/4 cup flour",
        "1 tablespoon paprika",
        "2 teaspoons salt",
        "2 teaspoons lemon pepper",
        "1/2 teaspoon cayenne pepper",
      ]},
    ],
    instructions: [
      { group: null, items: [
        "Place all ingredients in a plastic bowl with a lid or in a brown paper lunch bag. Shake vigorously to mix all ingredients.",
        "Drop cleaned and washed fish fillets into the bowl or bag filled with cornmeal mix and shake vigorously again to coat. Drop fish into canola or peanut oil heated to 375°F to deep fry for 5-7 minutes, or until fish is golden brown.",
      ]},
    ],
    notes: [
      "For an extra flavor kick, add 1/2 teaspoon garlic powder and 1/2 teaspoon onion powder to the cornmeal mix.",
      "Nutrition below reflects all of the cornmeal mix; the fillet value varies depending on size and type of fish.",
    ],
    nutrition: { title: "Nutrition Facts (whole batch of mix)", items: ["Calories: 810 kcal", "Carbohydrates: 156g", "Protein: 21g", "Fat: 12g", "Sodium: 3112mg", "Sugar: 4g"] },
  },
  {
    id: "pumpkin-pie",
    title: "Pumpkin Pie with Sugared Cranberries",
    category: "desserts",
    meta: { Prep: "45 minutes (plus overnight for cranberries)", Cook: "55–60 minutes", Serves: "8–10" },
    ingredients: [
      { group: "Sugared Cranberries", items: [
        "1 cup (100g) fresh cranberries (not frozen)",
        "3/4 cup (180ml) water",
        "1 and 1/4 cups (250g) granulated sugar, divided",
      ]},
      { group: "Pie Crust", items: [
        "Homemade Pie Dough (full recipe for 2 crusts: bottom and leaf decor)",
        "Egg wash: 1 large egg beaten with 1 tablespoon milk",
      ]},
      { group: "Pumpkin Filling", items: [
        "One 15-ounce can (425g) pumpkin puree",
        "3 large eggs",
        "1 and 1/4 cups (250g) packed light or dark brown sugar",
        "1 tablespoon (8g) cornstarch",
        "1/2 teaspoon salt",
        "1 and 1/2 teaspoons ground cinnamon",
        "1/2 teaspoon ground ginger",
        "1/4 teaspoon ground or freshly grated nutmeg",
        "1/8 teaspoon ground cloves",
        "1/8 teaspoon fresh ground black pepper",
        "1 cup (240ml) heavy cream",
        "1/4 cup (60ml) milk",
      ]},
    ],
    instructions: [
      { group: "Sugared Cranberries (Start Night Before)", items: [
        "Place cranberries in a large heatproof bowl.",
        "Heat water and 3/4 cup sugar in saucepan until sugar dissolves.",
        "Cool syrup 5 minutes, pour over cranberries, stir.",
        "Cover, rest 15 minutes.",
        "Transfer cranberries to lined baking sheet, dry 1 hour.",
        "Toss in remaining 1/2 cup sugar.",
        "Dry again 1+ hour. Store in refrigerator up to 3 days.",
      ]},
      { group: "Pie Crust", items: [
        "Preheat oven to 375°F (190°C).",
        "Roll dough into 12-inch circle.",
        "Place in 9×2-inch deep dish pie dish.",
        "Crimp or flute edges, brush with egg wash.",
        "Line with parchment, fill with weights.",
        "Par-bake 10 minutes.",
        "Remove weights, prick bottom, bake 7-8 minutes more.",
      ]},
      { group: "Filling and Assembly", items: [
        "Whisk together pumpkin, eggs, and brown sugar; add cornstarch, salt, and spices; stir in cream and milk.",
        "Pour into warm crust (fill 3/4 full).",
        "Bake 55-60 minutes: cover edges with foil after 25 minutes; center should be slightly wobbly; check doneness starting at 50 minutes.",
        "Cool completely (3+ hours) before decorating.",
        "Garnish with sugared cranberries and pie crust leaves.",
      ]},
    ],
    notes: ["Cover leftovers tightly. Store in refrigerator up to 5 days."],
  },
  {
    id: "sourdough-starter",
    title: "Sourdough Starter",
    category: "breakfast",
    source: "Source: Natasha Kravchuk | NatashasKitchen.com",
    meta: { "Active Time": "About 10 minutes a day", "Total Time": "6–7 days", Makes: "1 starter" },
    ingredients: [
      { group: null, items: [
        "100 g whole grain rye flour or whole wheat flour, preferably organic (100g = 3/4 cup)",
        "500 g all-purpose flour — preferably organic, unbleached — used to maintain and feed the starter",
        "1 qt filtered or spring water, room temperature",
      ]},
    ],
    instructions: [
      { group: "Day 1: Make Your Starter", items: [
        "Record the weight of your jar in grams before you add anything, and label the jar with your starting date for easier tracking.",
        "Add 100 grams (3/4 cup) whole wheat or rye flour and 100 grams (1/2 cup) water. Stir together thoroughly with a fork (it will be very thick), scrape down the sides with a spatula. Cover with a loose-fitting lid and let it rest at room temperature for 24 hours. Put a rubber band around the jar to mark the growth of your starter.",
      ]},
      { group: "Day 2: No Changes Noted", items: [
        "Likely nothing is happening — you might see tiny bubbles, or it will look the same. Let it rest for another 24 hours.",
      ]},
      { group: "Day 3: Visible Growth and Bubbles", items: [
        "Remove and discard half of the starter (in the trash, not the sink, so it doesn't affect the plumbing) — you should have 100 grams (1/2 cup) left. Add 100 grams (3/4 cup) all-purpose flour and 100 grams (1/2 cup) room-temp water. Stir thoroughly, scrape down the sides, cover loosely, and rest at room temperature for 24 hours.",
      ]},
      { group: "Day 4: A Lot of Bubbles", items: [
        "Remove and discard all but 100 grams of starter. Add 100 grams (3/4 cup) all-purpose flour and 100 grams (1/2 cup) room-temperature water. Stir thoroughly, scrape down the sides, cover loosely, and rest 24 hours.",
        "If your starter seems to slow down for no apparent reason on day 4, just keep feeding it — it will turn back around.",
      ]},
      { group: "Day 5: Visible Growth and Bubbles", items: [
        "Remove and discard all but 100 grams of starter. Add 100 grams (3/4 cup) all-purpose flour and 100 grams (1/2 cup) room-temperature water. Stir thoroughly, scrape down the sides, cover loosely, and rest 24 hours.",
      ]},
      { group: "Day 6–7: Starter May Double or More", items: [
        "Remove and discard all but 100 grams of starter. Add 100 grams (3/4 cup) all-purpose flour and 100 grams (1/2 cup) room-temperature water. Stir thoroughly, scrape down the sides, cover loosely, and rest until more than doubled in volume.",
      ]},
      { group: "Testing Your Starter", items: [
        "When ready, it should peak between 4-6 hours and start to recede after 12 hours. It should smell sour and pleasant. Drop a dollop into a bowl of water — if it floats, it's healthy enough to use. If it isn't ready by day 7, keep feeding it on this same schedule; it may just need more time depending on your flour and environment.",
      ]},
      { group: "How to Maintain Your Starter", items: [
        "Frequent bakers: store at room temperature. Discard and feed every 24 hours. To use, feed and wait for the starter to reach its peak (4-6 hours), then remove the portion needed for the recipe.",
        "Casual bakers (weekly): store in the fridge. Once a week, discard and feed, then rest at room temperature 1-2 hours before returning to the fridge. To bake, remove from the fridge, bring to room temperature overnight, discard and feed, then remove the portion needed once it peaks — feed and refrigerate the rest.",
      ]},
    ],
    notes: [
      "Temperature is key: ideal growing temperature is 68–75\°F. A cold kitchen may take longer — consider a warmer spot or lukewarm (85°F) water.",
      "Use non-chlorinated water: chlorine can hinder yeast and bacteria growth. Use filtered or spring water, or dechlorinate tap water by boiling and cooling it, or letting it sit out uncovered for a day.",
      "Consistency helps: try to feed your starter at the same time each day.",
      "Patience is essential: starters vary in how quickly they develop. Don't rush it with too much warmth, or you can exhaust the yeast.",
    ],
  },
  {
    id: "bread-butter-pickles",
    title: "Bread and Butter Pickles (Canning Method)",
    category: "sides",
    source: "Source: America's Test Kitchen",
    meta: { Prep: "30 minutes + 3 hours salting", "Process Time": "30 minutes", Total: "About 2 days (mostly hands-off)", Makes: "4 pint jars" },
    ingredients: [
      { group: "Vegetables", items: [
        "2 lbs small Kirby pickling cucumbers, ends trimmed, sliced into 1/4-inch rounds",
        "1 onion, quartered and thinly sliced",
        "1 red bell pepper, seeds and ribs removed, cut into thin matchsticks",
        "2 tablespoons canning and pickling salt (or plain kosher salt — avoid iodized salt or anti-caking agents)",
      ]},
      { group: "Brine", items: [
        "3 cups apple cider vinegar",
        "2 cups granulated white sugar",
        "1 cup water",
        "1 tablespoon yellow mustard seeds",
        "3/4 teaspoon turmeric",
        "1/2 teaspoon celery seeds",
        "1/4 teaspoon ground cloves",
      ]},
      { group: "For Canning", items: [
        "4 pint-size canning jars with new lids and rings",
        "1/8 teaspoon Pickle Crisp (calcium chloride) per jar",
      ]},
    ],
    instructions: [
      { group: "Prep the Vegetables", items: [
        "Trim about 1/16 inch off both ends of each cucumber (this removes the blossom end, which contains an enzyme that softens pickles over time). Slice into 1/4-inch rounds.",
        "Quarter the onion and slice thin. Add to a large bowl with the cucumbers.",
        "Cut the top and bottom off the bell pepper, slice down the sides to leave the seeds and ribs behind, then cut into thin matchsticks. Add to the bowl.",
        "Sprinkle in the salt and mix in with your hands. Cover and refrigerate about 3 hours to draw out excess moisture.",
      ]},
      { group: "Prep the Jars", items: [
        "Fit a rack in the bottom of a large canning pot so the jars don't sit directly on the bottom (they can crack when the water boils). Add the 4 jars and fill the pot with water to cover.",
        "Bring to a simmer over medium-high heat, then turn off the heat, cover, and let the jars sit in the warm water until ready to fill.",
      ]},
      { group: "Make the Brine", items: [
        "Combine the apple cider vinegar, sugar, and water in a saucepan.",
        "Add the mustard seeds, turmeric, celery seeds, and ground cloves.",
        "Bring to a boil over medium-high heat, then cover and set aside to stay warm.",
      ]},
      { group: "Fill and Seal the Jars", items: [
        "Drain the salted vegetables in a colander — don't rinse, the salt stays in for seasoning. Shake well, then pat dry with paper towels to remove surface moisture.",
        "Remove the warm jars from the water with a jar lifter, drain, and turn upside down briefly on a towel to dry.",
        "Add 1/8 teaspoon Pickle Crisp to the bottom of each jar.",
        "Pack the vegetables evenly into the jars (a canning funnel helps).",
        "Bring the brine back to a boil, then ladle it over the vegetables in each jar, leaving about 1/2 inch of headspace.",
        "Run a skewer around the inside of each jar to dislodge trapped air bubbles, then top off the brine back to about 1/2 inch headspace (the first ridge on the jar).",
        "Wipe the rims clean, then add a new lid and a ring turned just \"fingertip tight\" — tight enough to seal, loose enough to let air escape during processing.",
      ]},
      { group: "Process the Jars", items: [
        "Make sure the water in the canning pot is still warm (120–140°F), then use a jar lifter to lower the filled jars back into the pot. Make sure there's about an inch of water covering them.",
        "Bring the water to 185°F and process for 30 minutes at that temperature — keeping it between 180–185°F (below a full boil) is what keeps the pickles crisp instead of mushy, since pectin starts breaking down above 185°F.",
        "Remove the jars and let them cool undisturbed for 24 hours.",
      ]},
      { group: "Check the Seal & Store", items: [
        "After 24 hours, remove the ring and press the center of the lid — it should feel tight and slightly indented, meaning it formed a good vacuum seal.",
        "Store sealed jars in a cool, dark place. Refrigerate after opening.",
      ]},
    ],
    notes: [
      "Use small, firm Kirby cucumbers for the best crunch — larger cucumbers have bigger seeds that can separate and cause the cucumber to fall apart during pickling. Fresher cucumbers make crisper pickles.",
      "Use canning and pickling salt or plain kosher salt — avoid iodized salt or salt with anti-caking agents, which can cloud the brine.",
      "Pickle Crisp (calcium chloride) helps keep pickles crunchy; measuring it directly into each jar ensures every jar gets the right amount.",
      "Always use new lids each time — rings can be reused, but the seal depends on a fresh lid.",
      "The brine should taste tart-sweet, not syrupy — this recipe uses noticeably less sugar than many bread and butter pickle recipes.",
    ],
  },
  {
    id: "dream-biscuits",
    title: "Dream Biscuits (Drop Cream Biscuits)",
    category: "breakfast",
    source: "Source: America's Test Kitchen",
    meta: { Prep: "15 minutes", Bake: "10–12 minutes", Makes: "10 biscuits" },
    ingredients: [
      { group: "Dry Ingredients", items: [
        "3 cups all-purpose flour",
        "4 teaspoons sugar",
        "1 tablespoon baking powder",
        "1/4 teaspoon baking soda",
        "1 1/4 teaspoons salt",
      ]},
      { group: "Wet Ingredients", items: [
        "2 cups heavy cream (about 36% fat)",
      ]},
      { group: "For Serving", items: [
        "2 tablespoons unsalted butter, melted",
      ]},
    ],
    instructions: [
      { group: "Mix the Dough", items: [
        "Whisk together the flour, sugar, baking powder, baking soda, and salt in a large bowl until combined.",
        "Heat the heavy cream in the microwave to about 95–100°F, roughly 60-90 seconds. This melts the butterfat suspended in the cream and thins it out enough to make a scoopable dough — don't skip this step, cold cream makes a dough that's too stiff and won't spread properly in the oven.",
        "Stir the warm cream into the dry ingredients with a spatula until completely smooth. Unlike most biscuit doughs, this one can be mixed thoroughly without worrying about overworking the gluten — the high fat content coats the flour and keeps the crumb tender.",
      ]},
      { group: "Portion and Bake", items: [
        "Preheat the oven to 450°F before you begin mixing — it needs the most lead time of anything in this recipe.",
        "Lightly spray a 1/3-cup measure with cooking spray. Scoop the dough and drop it straight down onto a baking sheet to form a neat mound. Re-spray the measure as needed if the dough starts to stick. You should get about 10 biscuits.",
        "If any biscuits fall over or look uneven, reshape them with your fingers — the dough won't stick since it's coated in spray.",
        "Bake on the upper-middle rack for 10-12 minutes, rotating the pan halfway through, until golden brown on top.",
        "Brush the warm biscuits with the melted butter for flavor and a bit of shine.",
        "Let cool about 5 minutes before serving warm.",
      ]},
    ],
    notes: [
      "The key twist: warming the cream to 95–100°F melts its butterfat so the dough turns soft and scoopable. The same recipe made with cold cream turns dry and stiff instead of smooth.",
      "These come out tender and not dry inside, with good crust flavor from the cream's fat content, even though it's made with regular all-purpose flour.",
      "Great alongside soup or chili, or split and served with jam.",
    ],
  },
  {
    id: "sourdough-focaccia",
    title: "Simple Sourdough Focaccia",
    category: "breakfast",
    source: "Source: Alexandra Stafford | AlexandraCooks.com",
    meta: { Prep: "25 minutes (plus rises)", Rise: "8–24 hours total", Bake: "25 minutes", Makes: "1 loaf" },
    ingredients: [
      { group: null, items: [
        "50–100 g (1/4 to 1/2 cup) active sourdough starter (use 50g in summer, 100g in winter)",
        "10 g (about 2 1/2 teaspoons) kosher salt",
        "430–440 g water (1 3/4 cups to 1 3/4 cups + 2 tablespoons), room temperature",
        "512 g (about 4 cups) bread flour",
        "3 tablespoons extra-virgin olive oil, divided, plus more for drizzling",
        "Flaky sea salt, such as Maldon, for topping",
      ]},
    ],
    instructions: [
      { group: "Mix and First Rise", items: [
        "Place the starter, salt, and water in a large bowl. Stir with a spatula to combine — it doesn't have to be uniformly mixed. Add the flour and mix again until completely incorporated.",
        "If time permits, perform one \"fold\" 30 minutes after mixing: reach into the bowl, pull the dough up and into the center, turn the bowl a quarter turn, and repeat 8 to 10 times.",
        "Drizzle with a splash of olive oil and rub to coat. Cover the bowl and let rise at room temperature (70°F) for 4 to 18 hours, until nearly doubled — in summer this takes about 4-6 hours, in winter 12-18 hours. Rely on visual doubling rather than the clock; a straight-sided container makes this easier to judge.",
      ]},
      { group: "Shape and Second Rise", items: [
        "Pour 2 tablespoons of olive oil into a 9x13-inch pan.",
        "Drizzle the dough with 1 tablespoon olive oil. Gently deflate it and release it from the sides of the bowl, then scoop it into the center of the oiled pan. Fold the dough envelope-style (top to bottom, side to side) into a rough rectangle, and flip so the seam side is down.",
        "Rub the top with oil and leave uncovered for 4 to 6 hours, until puffy and nearly doubled.",
      ]},
      { group: "Bake", items: [
        "Heat oven to 425°F. Lightly oil your hands and use all ten fingers to press dimples into the dough, stretching it to nearly fill the pan.",
        "Sprinkle generously with flaky sea salt.",
        "Bake about 25 minutes, until golden all around. Cool on a rack at least 20 minutes before slicing.",
      ]},
    ],
    notes: [
      "Use 50g starter in summer (faster rise, check every couple hours); use 100g in winter and plan for a longer first rise.",
      "Chlorine can slow sourdough — let tap water sit out at room temperature for a day, or use filtered/spring water.",
      "If your kitchen is humid, start with the lower end of the water range (430g); all-purpose flour also needs slightly less water than bread flour.",
      "If the first rise goes a bit past double, don't worry — the focaccia will still turn out light and delicious.",
    ],
  },
  {
    id: "coconut-custard-pie",
    title: "Coconut Custard Pie",
    category: "desserts",
    source: "Source: Allrecipes, submitted by Lesley (adapted)",
    meta: { Prep: "10 minutes", Cook: "40–50 minutes", Serves: "8", Yield: "1 (9-inch) pie" },
    ingredients: [
      { group: null, items: [
        "3/4 cup white sugar",
        "1/2 cup butter",
        "2 large eggs",
        "2 tablespoons all-purpose flour",
        "1 cup milk",
        "1 cup flaked coconut",
        "1 teaspoon vanilla extract",
        "1/2 teaspoon ground cinnamon",
        "1/8 teaspoon ground nutmeg, plus more for dusting",
        "1 (9-inch) unbaked pie crust",
        "1 tablespoon flaked coconut, for topping",
      ]},
    ],
    instructions: [
      { group: null, items: [
        "Gather all ingredients. Preheat the oven to 350°F (175°C).",
        "Beat together the sugar, butter, and eggs in a large bowl with an electric mixer on low speed.",
        "Blend in the flour. Mix in the milk, 1/2 cup at a time. Add the coconut flakes, vanilla, cinnamon, and nutmeg; mix well.",
        "Pour the filling into the unbaked pie crust. Sprinkle the top with the remaining 1 tablespoon of coconut flakes.",
        "Bake until the filling is set and the coconut is toasted, 40 to 50 minutes.",
        "Cool before slicing. Serve with whipped cream and a dusting of nutmeg.",
      ]},
    ],
    notes: [
      "Adapted from the original recipe: sugar reduced from 1 1/2 cups to 3/4 cup, with 1/2 teaspoon cinnamon and 1/8 teaspoon nutmeg added to the filling for a warmer, less sweet flavor.",
    ],
  },
  {
    id: "creamy-spinach-chicken",
    title: "Creamy Spinach Chicken",
    category: "main",
    source: "Source: The Kitchn",
    meta: { Prep: "10 minutes", Cook: "25 minutes", Serves: "3 to 4" },
    ingredients: [
      { group: null, items: [
        "1 medium yellow onion",
        "4 cloves garlic",
        "1 pound thin-cut boneless, skinless chicken breasts (about 3)",
        "1 teaspoon kosher salt, plus more as needed",
        "1/2 teaspoon freshly ground black pepper",
        "1/4 cup all-purpose flour",
        "2 tablespoons olive oil",
        "1/2 cup low-sodium chicken broth",
        "1/2 cup heavy cream",
        "1/4 cup sour cream",
        "1 tablespoon soy sauce",
        "1 teaspoon apple cider vinegar",
        "1/4 teaspoon garlic powder",
        "1/4 teaspoon red pepper flakes",
        "1 tablespoon unsalted butter",
        "1 (5-ounce) package baby spinach (5 packed cups)",
        "Cooked pasta or steamed rice, for serving",
      ]},
    ],
    instructions: [
      { group: null, items: [
        "Thinly slice the onion and finely chop the garlic.",
        "Pat the chicken breasts dry with paper towels. Season all over with the kosher salt and black pepper. Place the flour on a plate. Working with one piece of chicken at a time, press into the flour until evenly coated all over. Place on a plate in a single layer.",
        "Heat the olive oil in a 10-inch skillet over medium heat until shimmering. Add half of the chicken and cook until lightly browned, about 1 1/2 minutes per side (the chicken will not be cooked through). Transfer to a plate and repeat cooking the remaining chicken.",
        "Meanwhile, place the chicken broth, heavy cream, sour cream, soy sauce, apple cider vinegar, and garlic powder in a medium bowl or liquid measuring cup and whisk to combine.",
        "When the chicken is ready, add the onion, butter, and a pinch of kosher salt to the now-empty pan. Reduce the heat to medium-low and cook, scraping up any browned bits from the bottom of the pan with a wooden spoon, until the onion is starting to brown, 5 minutes. Add the garlic and red pepper flakes, and cook until fragrant, about 30 seconds.",
        "Add the chicken broth mixture and stir to combine. Cook until the sauce starts to thicken, 3 to 4 minutes. Gradually add the baby spinach and cook, stirring often, until the spinach is wilted.",
        "Return the chicken and any accumulated juices on the plate to the skillet. Increase the heat to medium-high and cook until the chicken is cooked through and coated with sauce, 4 to 5 minutes. Serve over cooked pasta or rice.",
      ]},
    ],
    notes: [
      "Use thin chicken cutlets so they absorb the sauce well. To prepare your own: cover chicken breasts with plastic wrap and pound with a rolling pin until thin, then dredge in flour before cooking.",
      "Great served over rice or noodles, with a simple green salad on the side.",
    ],
  },
  {
    id: "lemon-garlic-chicken",
    title: "Lemon Garlic Chicken",
    category: "main",
    source: "Source: The Kitchn",
    meta: { Prep: "5 minutes", Cook: "18 to 21 minutes", Serves: "4" },
    ingredients: [
      { group: null, items: [
        "4 boneless, skinless chicken breasts (about 2 pounds total), pounded to 1/2-inch thickness",
        "1/2 teaspoon kosher salt, plus more for seasoning",
        "1/4 teaspoon freshly ground black pepper, plus more for seasoning",
        "1 tablespoon olive oil",
        "3 tablespoons unsalted butter",
        "1 small shallot, finely chopped",
        "4 cloves garlic, minced",
        "2 tablespoons all-purpose flour",
        "1 cup half-and-half or whole milk",
        "1/2 cup low-sodium chicken broth",
        "Juice of 1 medium lemon (about 3 tablespoons)",
        "2 tablespoons chopped fresh parsley leaves",
        "1 small lemon, thinly sliced",
      ]},
    ],
    instructions: [
      { group: null, items: [
        "Thoroughly dry the chicken with paper towels. Generously season all over with salt and pepper.",
        "Heat the oil in a 10-inch or larger skillet over medium-high until shimmering. Working in batches if needed, add the chicken and sear until deeply browned on the bottom, 6 to 7 minutes. Flip with tongs and sear the other side until browned, 6 to 7 minutes. Transfer the chicken to a plate; set aside.",
        "Reduce the heat to medium and add the butter. When melted, add the shallot, garlic, 1/2 teaspoon salt, and 1/4 teaspoon pepper and cook, stirring occasionally, until just starting to soften, about 1 minute. Add the flour, stir to evenly coat the shallots and garlic, and cook for 1 minute more.",
        "Stir in the half-and-half or milk and broth until no lumps from the flour remain, making sure to scrape up any browned bits from the bottom of the pan. Bring to a boil. Reduce the heat to a simmer. Return the chicken to the pan and simmer until the sauce is thickened enough that it coats the back of a spoon and the chicken is cooked through, 3 to 4 minutes. Stir the lemon juice into the sauce. Garnish with the parsley and lemon slices and serve immediately.",
      ]},
    ],
  },
  {
    id: "creamy-orzo-chicken-zucchini",
    title: "One-Pan Creamy Orzo Chicken and Zucchini",
    category: "main",
    source: "Source: The Kitchn",
    meta: { Prep: "15 minutes", Cook: "30 to 35 minutes", Serves: "4" },
    ingredients: [
      { group: null, items: [
        "1 large shallot or 1/2 small yellow onion",
        "2 cloves garlic",
        "1 pound zucchini (2 medium)",
        "1 medium lemon",
        "1 ounce Parmesan cheese (1/2 cup firmly packed freshly grated or 1/3 cup store-bought grated)",
        "1 1/2 pounds boneless, skinless chicken thighs (5 to 6)",
        "2 teaspoons kosher salt, divided",
        "1/4 teaspoon freshly ground black pepper",
        "3 tablespoons olive oil, divided",
        "10 ounces dried orzo pasta (about 1 1/2 cups)",
        "2 cups low-sodium chicken broth",
        "2 cups whole milk",
      ]},
    ],
    instructions: [
      { group: null, items: [
        "Thinly slice the shallot or onion (about 1/2 cup). Mince the garlic. Trim the zucchini, halve lengthwise (quarter lengthwise if wider than 1 1/2 inches), then cut crosswise into 1/4-inch-wide pieces (about 3 1/2 cups). Finely grate the zest of the lemon (about 1 loosely packed tablespoon). Juice the lemon until you have 2 tablespoons. Finely grate the Parmesan (about 1/2 cup lightly packed) if needed, or measure out 1/3 cup store-bought.",
        "Pat the chicken thighs dry with paper towels. Season all over with 1/2 teaspoon of the kosher salt and the black pepper.",
        "Heat 1 tablespoon of the olive oil in a 12-inch or larger high-sided skillet or Dutch oven over medium-high heat until shimmering. Add the chicken and sear until browned on the bottom, 5 to 6 minutes. Flip with tongs and sear until the second side is browned, 2 to 3 minutes more. Transfer to a plate. The chicken will not be cooked through yet.",
        "Add the remaining 2 tablespoons olive oil, shallot, and zucchini to the skillet. Cook, stirring occasionally, until softened, about 3 minutes. Add the orzo, garlic, and lemon zest, and stir to coat with the oil. Cook until lightly toasted and fragrant, 1 to 2 minutes.",
        "Add the chicken broth, whole milk, and the remaining 1 1/2 teaspoons kosher salt. Stir to combine, scraping up any browned bits from the bottom of the pan with a wooden spoon.",
        "Bring to a boil over medium-high heat, stirring frequently to keep the orzo from sticking. Reduce the heat to maintain a simmer. Nestle the chicken into the orzo and pour in any accumulated juices. Cook uncovered, making sure the orzo is in the liquid at all times and stirring frequently, until the orzo is tender, the chicken is cooked through and registers at least 165°F on an instant-read thermometer, and most of the liquid is absorbed, 10 to 12 minutes.",
        "Remove the pan from the heat. Add the lemon juice and Parmesan and stir to combine. Taste and season with more kosher salt if needed. Let sit for 5 minutes before serving.",
      ]},
    ],
  },
];
